import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/utils/AuthProvider";
import StarCanvas from "./_components/Home/StarBackground";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#000000] bg-[radial-gradient(#cccccc33_1px,#000000_1px)] bg-[size:40px_50px]  `}>
        <AuthProvider>
        {/* <StarCanvas/> */}
        {children}
      
        </AuthProvider>
      
      </body>
    </html>
  );
}
// bg-[#030014]